import { Montserrat } from 'next/font/google'
import './globals.css'
import PlayMusicBg, {PlayAudio} from "@/components/SoundPlayer";
import AudioPlayer from "@/components/AudioPlayer";

const inter = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="ru">
        <body className="h-full w-full">
          <header>
          </header>

          <main className={inter.className}>
            <div className={"container h-full mx-auto"}>
              {children}
            </div>
          </main>

          <footer>
          </footer>
        </body>
      </html>
  );
}
